SCREEN_WIDTH = 700
SCREEN_HEIGHT = 500
PADDLE_WIDTH = 10
PADDLE_HEIGHT = 100
BALL_WIDTH = 10
BALL_HEIGHT = 10
PADDLE_SPEED = 5
FONT_SIZE = 72
score_left_offset = 100
score_top_offset = 30
SCORE_LEFT = (score_left_offset, score_top_offset)
SCORE_RIGHT = (SCREEN_WIDTH - score_left_offset - FONT_SIZE, score_top_offset)
